WEBDRIVER_PATH = ".\Drivers\chromedriver"
#Drivers
# 1e, chrome
#Browsers="ie"
Browsers="chrome"

TodayDeals="//*[@id='nav-xshop']/a[2]"
Dealimage= "(//*[@id='dealImage']/div/div/div[2])[2]"
FirstDealImage="//*[@id='octopus-dlp-asin-stream']/ul/li[1]/span/div/div[1]/a/div"
AddToCart="add-to-cart-button"
ProceedToCheckout="hlb-ptc-btn-native"

BuyAgain = "//*[@id='nav-xshop']/a[9]"
ThirdImage = "//*[@id='anonCarousel1']/ol/li[3]/div/div[1]/a/div/img"
SaveForLater = "(//div[4]/div/div[1]/div/div/div[2]/div[1]/span[3]/span/input)[1]"
MoveToCart = "//input[contains(@value,'Move to cart')]"

ClickOnPrime ="//*[@id='nav-link-prime']/span[1]"
ClickOnEntertainment ="//*[@id='prime-benefit-cards']/div[2]/div[1]/div"
ClickOnAmazonmusicUnlimited ="#anonCarousel2 > ol > li:nth-child(5) > div > a > div.a-row.card-image > img"
ClickOnGetStarted ="#dmusicLandingButton > span > a > span"

ClickOnAll = "//*[@id='nav-hamburger-menu']/span"
ClickOnAppstoreAndriod = "//*[@id='hmenu-content']/ul[1]/li[14]/a/div"
ClickOnAllAppsAndGames = "#hmenu-content > ul.hmenu.hmenu-visible.hmenu-translateX > li:nth-child(3) > a"
ClickOnLast30Days = "//*[@id='s-refinements']/div[1]/ul/li[1]/span/a/span"
ClickOnFirstImageApp = "//*[@id='search']/div[1]/div[2]/div/span[3]/div[2]/div[1]/div/span/div/div/span/a/div/img"
ClickOnContinue = "//*[@id='masrw-get-app-button-announce']"
ISignout = "//*[@id='nav-item-signout']/span"

Clickonbestseller ="//*[@id='nav-xshop']/a[6]"
Clickonnewreases ="//*[@id='zg_tabs']/ul/li[2]/div/a"
Clickonmoversandshakers="//*[@id='zg_tabs']/ul/li[3]/div/a"
Clickonmostwishedfor="//*[@id='zg_tabs']/ul/li[4]/div/a"
Clickongiftideas="//*[@id='zg_tabs']/ul/li[5]/div/a"
Clickonfirstimage="//*[@id='zg_left_col1']/div[1]/div[2]/div/div[2]/a/div[1]/img"
Clickonaddingcart="add-to-cart-button"
Clickonproceedtocheckout="#hlb-ptc-btn-native"

Findagift ="//*[@id='nav-xshop']/a[9]"
Mothersday ="//*[@id='notification-provider']/div/div/div[1]/div/a[1]/div/div[2]/span"
Jewelleryandwatches ="//*[@id='sobe_d_aw_2_2']/div/a"
Bracelet ="//*[@id='a-page']/div[2]/div[2]/div[1]/div[4]/div[1]/div/div[1]/div[1]/div/div[2]/div[1]/a/h2"
Style ="//*[@id='a-autoid-9-announce']/div/div[1]/p"
Buystyle ="buy-now-button"